name: nest-next-to-do-app-prod

services:
  database:
    image: postgres:latest
    container_name: nest-next-to-do-app_postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env.prod
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data
    networks:
      - nest-next-to-do-network

  backend:
    build:
      context: .
      dockerfile: .docker/server/Dockerfile.prod
    container_name: nest-next-to-do-app_backend
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env.prod
    depends_on:
      - database
    networks:
      - nest-next-to-do-network

  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile.prod
    container_name: nest-next-to-do-app_frontend
    restart: always
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    env_file:
      - .env.prod
    networks:
      - nest-next-to-do-network

volumes:
  database:

networks:
  nest-next-to-do-network:
